# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClearWaterMark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClearWaterMark

  target 'ClearWaterMarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClearWaterMarkUITests' do
    # Pods for testing
  end

  pod 'Masonry'
  pod 'SDWebImage', '~> 3.7.2'
  pod 'AFNetworking', '~> 3.1.0'

end
